# Welcome to Jekyll!

# Site settings
title: karltaylor.me
description: The work of Karl Taylor. A Front-End Web Developer based in London.
baseurl: "http://karltaylor.github.io/karltaylor.me" # the subpath of your site, e.g. /blog
url: "http://karltaylor.me" # the base hostname & protocol for your site

twitter_username: karltaylor_
github_username: karltaylor
author: Karl Taylor
email: karl_taylor@me.com

# Build settings
markdown: kramdown

source: src
destination: _site
