#!/bin/bash

# colors
green=$'\e[32m'
red=$'\e[31m'
yellow=$'\e[33m'
rs=$'\e[0m'

### vars
get_branch_name=$(git symbolic-ref -q HEAD)
Length=8
branch_name=${get_branch_name:11:Length}

if [ $branch_name != develop ]
then
  echo $red"ERROR: You are not on the develop branch. Commit changes and merge into develop and re-run ./deploy"
  read -r -p $yellow"Would you like to switch to the develop branch now? [y/N] " response
  if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
  then
      echo $yellow'Switching to develop branch'$rs
      git co develop
  else
      return
  fi
else
  echo $green'---------------------'
  echo $green'Running Deploy Script'
  echo $green'---------------------'
  git co gh-pages
  git merge develop
  git push --all origin
  echo $green'Successfully Deployed'
fi
